export KMEANS_RUN_INTERACTIVE=true
export KMEANS_PROCESSES_MIN=1
export KMEANS_PROCESSES_MAX=20
export KMEANS_PROCESSES_STEP=10
export KMEANS_DEBUG=warn
export KMEANS_CLUSTERS=22
export KMEANS_MAX_ITERATIONS=200
export KMEANS_PROG_NUM=1
export KMEANS_JUTLAND_SIZE=50
export KMEANS_MAX_POINTS=100
export KMEANS_REPORT=test.csv

printenv | grep KMEANS_