unset KMEANS_RUN_INTERACTIVE
export KMEANS_PROCESSES_MIN=1
export KMEANS_PROCESSES_MAX=200
export KMEANS_PROCESSES_STEP=20
export KMEANS_DEBUG=warn
export KMEANS_CLUSTERS=22
export KMEANS_MAX_ITERATIONS=200
export KMEANS_PROG_NUM=1
unset KMEANS_JUTLAND_SIZE
unset KMEANS_MAX_POINTS
export KMEANS_REPORT=jutland_metrics_main.csv

printenv | grep KMEANS_
