export KMEANS_PROCESSES=10
export KMEANS_DEBUG=info
export KMEANS_IN=jutland_500.csv
export KMEANS_TEST=jutland_500_clustered_knime.csv
export KMEANS_CLUSTERS=22
export KMEANS_MAX_ITERATIONS=200
export KMEANS_MAX_POINTS=1000
export KMEANS_PROG_NUM=1